### ISSUE TITLE
[Accessibility][ConfigPanelTextLink] The disclosure control does not follow the established design pattern

### ISSUE THREAD

**Issue by mnischay** [awslabs/iot-app-kit#2363]
#### Notes and Advice 
The Disclosure widget has the following issues:
 
The "Create link" checkbox is defined as the descendant of "Link" disclosure (<div> with role="button") control due to which following screen reader issues are observed:
 
Dual name as "Link Create link Create link Button collapsed" is being announced on disclosure control.
Dual name and role information as "Link Create link Create link Button expanded Create link checkbox checked" is being announced on the checkbox control in backward navigation

#### Recommendation 
Ensure that the "Create link" checkbox should not be defined as the descendant of "Link" disclosure (<div> with role="button") control.
 
The below screen reader observation is expected:
 
On disclosure control: "Link button collapsed/expanded"
On checkbox control: "Create link checkbox checked/not checked"
 Resources 
ARIA Authoring Practices [Disclosure (Show/Hide) Design Pattern](https://www.w3.org/WAI/ARIA/apg/patterns/disclosure/)
[Disclosure Widgets](https://adrianroselli.com/2020/05/disclosure-widgets.html)

**Comment by gmuralidharreddy** [comment]
The issue of the 'Create link' being announced twice is not being reproduced with the screen reader. Please see the video

https://github.com/awslabs/iot-app-kit/assets/139960352/9083f117-b6f8-4ed3-9f79-14d82f2ed24a

**Comment by jmbuss** [comment]
The screenreader does announce "Link Create Link" since the component library is inferring the label from the html content. There is a property on the ExpandableSection component for setting the label - `headerAriaLabel`.

headerAriaLabel = "Text widget link settings"
headerDescription = "Configure the text widget to be a url link. Toggle the text as a link with the button."

The bigger accessibility problem is that focusing the "Create link" toggle and pressing enter does not actually toggle the text as a link. This will need to be fixed for the entire section to be considered accessible.
