### ISSUE TITLE
[Dashboard] making the decimal place value too large crashes dashboard

### ISSUE THREAD

**Issue by diehbria** [awslabs/iot-app-kit#2567]
When the decimal place settings is set to too large of a number, the dashboard crashes: 
```

RangeError: precision 123 out of range 
round number.js:20

```
![dec](https://github.com/awslabs/iot-app-kit/assets/77755322/e6ce4403-0c17-4d24-b0e8-6c35bc64ff8d)

```[tasklist]
### acceptance criteria
- [ ] prevent user from putting decimal place that will cause browser crash
```

**Comment by Kausar-HM** [comment]
Hi @nadeswal

In this ticket we have to add validation to 'Decimal places' input, so we added the same in way it works for other fields:
![image](https://github.com/awslabs/iot-app-kit/assets/154328164/fee47758-3ff9-4bbb-a9f9-a0aee0d89b5c)

Currently the 'Decimal places' label is to the left of the input, in the config panel all other fields have the label at top, so should we move 'Decimal places' to the top as well?

![image](https://github.com/awslabs/iot-app-kit/assets/154328164/6d593461-277c-4a5f-a764-95d695f17edf)

**Comment by nadeswal** [comment]
Here is the screenshot that you can use to replicate the design -
<img width="258" alt="Screenshot 2024-02-15 at 2 32 59 PM" src="https://github.com/awslabs/iot-app-kit/assets/141063047/c69cf156-8164-4c96-8c5e-22ba35a08c49">

**Comment by jmbuss** [comment]
This is what the team discussed and agreed on - We will keep the decimal places as it is in it's own separate section but modify the section name to "Format data" instead of decimal places. Please refer to the screenshot below -

![Screenshot 2024-03-20 at 2 20 08 PM](https://github.com/awslabs/iot-app-kit/assets/107281089/345d52e2-f1c9-428c-bc6b-5731fc683f6b)
