### ISSUE TITLE
@iot-app-kit/source-iotsitewise tries to aggregate string data using AVERAGE

### ISSUE THREAD

**Issue by NorbertNader** [awslabs/iot-app-kit#258]
**Describe the bug**
When requesting aggregated data and panning an error is thrown to the console and datapoints are missing.

**To Reproduce**
1. Go to testing ground and add a line chart with a query for a string property

```
            <iot-line-chart
              widgetId="line-chart"
              viewport={{ duration: '10m' }}
              queries={[
                this.query.timeSeriesData({
                  assets: [
                    {
                      assetId: DEMO_ASSET,
                      properties: [
                        {
                          propertyId: DEMO_STRING_PROPERTY,
                        },
                      ],
                    },
                    {
                      assetId: DEMO_ASSET,
                      properties: [
                        {
                          propertyId: DEMO_PROPERTY,
                        },
                      ],
                    },
                    {
                      assetId: DEMO_ASSET2,
                      properties: [
                        {
                          propertyId: DEMO_PROPERTY,
                        },
                      ],
                    },
                    {
                      assetId: DEMO_ASSET3,
                      properties: [
                        {
                          propertyId: DEMO_PROPERTY,
                        },
                      ],
                    },
                    {
                      assetId: DEMO_ASSET4,
                      properties: [
                        {
                          propertyId: DEMO_PROPERTY,
                        },
                      ],
                    },
                  ],
                }),
              ]}
            />
```

2. Zoom in on the line chart
3. Errors are thrown as shown in the recording and screenshots

**Expected behavior**
String data is should not be aggregated and always be raw.

**Screenshots**

https://user-images.githubusercontent.com/6397726/193126694-e36e5038-5b48-4374-bd87-77d6ef53d2b6.mov

<img width="1192" alt="Screen Shot 2022-09-29 at 12 38 00 PM" src="https://user-images.githubusercontent.com/6397726/193126184-31ab91ac-0ccc-4e67-afb4-c00b19019b0f.png">

**Comment by NorbertNader** [comment]
I was actually also requesting one more string stream. Looks like we are trying to aggregate string stream.

**Comment by boweihan** [comment]
String data can be aggregated (as `count`) but we don't currently have great support for string data in time-series charts. This is because [1] in most cases it doesn't make sense to display the string data (e.g. as a series on a line chart) and [2] we don't currently have support for specifying different aggregation types in `source-iotsitewise`.

I do agree that there is probably a better user experience when specifying asset properties that have data types which aren't supported by certain charts. Short term, this could take the form of better documentation and more descriptive error messages. Long term, we could add some form of asset type discovery and adjust behaviour accordingly (e.g. automatically select "COUNT" aggregation for string asset properties).
