### ISSUE TITLE
[Dashboard] broken aggregation and resolution dropdowns

### ISSUE THREAD

**Issue by diehbria** [awslabs/iot-app-kit#2605]
**Initial State**:
Resolution = Auto   Aggregation = Average

**issue** 1
steps:
1. begin with widget set to initial state and with added data streams
2. change aggregation to No Aggregation
3. change resolution to 1 minute 

**seen**: 
- console errors InvalidRequestException: 3 validation errors detected: Value '[]' at 'entries.1.member.aggregateTypes'
- 404 bad requests in network tab
- widget displays No Data Present message
- property panel sets aggregation to be Average

**issue 2**
steps: 
- begin with widget set to initial state and with added data streams
- leave the resolution as auto and change the aggregation to maximum

**seen:**
no change to the widget

**expected:**
data should change to match new aggregation

![image (14)](https://github.com/awslabs/iot-app-kit/assets/77755322/1ea373ae-a6ae-4671-aa93-1f539035cf74)

https://github.com/awslabs/iot-app-kit/assets/77755322/c35e124e-aa48-431e-a3b7-a72ba9cd9743

**Comment by jmbuss** [comment]
![aggregation-resolution-bug-2](https://github.com/awslabs/iot-app-kit/assets/107281089/114207d9-d798-49f5-906f-c24bb08a92ad)

Here is a reproduction of the second issue.

**Comment by jmbuss** [comment]
Were you able to fix the issue of the aggregation not being applied on change in the properties panel? Like in the gif I posted? Or is this screenshot why it isn't working?

**Comment by Chandru-HM** [comment]
@jmbuss Yes, I found the root cause but waiting for product confirmation on the expected. it's not working only when resolution is 'Auto' and Viewport is relative and less than 15 min.  in all other scenarios it's working. in this specific scenario, the existing logic returns 0 for resolution so changing aggregation is not updating the Chart.

**Comment by jmbuss** [comment]
Yes that makes sense. Let's get UX input on how to handle this. Will forward this over.

As for the error. Can you try reproducing this using the KPI widget? @corteggiano pointed out that it happens with KPI because it has a default of raw data + no aggregation and when you switch to 1min resolution it still doesn't have an aggregation and it breaks.


https://github.com/awslabs/iot-app-kit/assets/107281089/9be89516-52fc-4ee7-9902-bd24f6e6f8b1

**Comment by Chandru-HM** [comment]
sure, I saw the error in the console. am debugging

**Comment by Chandru-HM** [comment]
@jmbuss the KPI widget issue is fixed. looks like the aggregation is not updated properly.
