### ISSUE TITLE
Sufficiently Large models in Scene Composer will get rendered outside the visible range of the Viewer, resulting in a confusing customer experience

### ISSUE THREAD

**Issue by TheEvilDev** [awslabs/iot-app-kit#304]
**Describe the bug**
When you load a large size model in the Scene Viewer, the default camera logic can zoom so far out that the model itself is rendered outside the visible range of the viewer, resulting in it seeming not to have been rendered at all.

**To Reproduce**
1. Create a scene in TwinMaker with a very large (geometrically, not necessarily complexity) model
2. Open the Scene Viewer in Grafana or AppKit

**Expected behavior**

- Model should download and be rendered visually with the default camera position

**Screenshots**

<img width="1790" alt="Screenshot 2022-10-31 at 12 44 52" src="https://user-images.githubusercontent.com/689065/199072377-3bd4522e-42ff-4e17-81ce-73afffb0dc0b.png">

**Additional context**

**Comment by eercanayar** [comment]
This issue is fixed by updating the `Unit of Measure = millimeters` on the Scene Composer for my particular case.

<img width="426" alt="image (30)" src="https://user-images.githubusercontent.com/1220261/199091882-a8fab3c8-a130-4a25-a655-c5beebaae935.png">

We've figured out that the issue was the "Unit" of the model file (or TwinMaker's default choice of "defaulting to meters" for 3D rendering). After setting it to "millimeters", it started rendering as expected. I was able to replicate the same "full gray" rendering by setting it to "meters". So if you're facing the similar; try other options of the "Unit of Measure" .
In meantime, TwinMaker Scene Composer (or viewer / AppKit) should be somehow **guiding** to avoid this confusion.
